// Filter collections organized by category
export const FILTER_COLLECTIONS = {
  normal: [
    {
      id: "normal",
      name: "Normal",
      filter: {
        brightness: 100,
        contrast: 100,
        grayscale: 0,
        sepia: 0,
        saturate: 100,
        hueRotate: 0,
      },
    },
  ],
  classic: [
    {
      id: "mono",
      name: "Mono",
      filter: {
        brightness: 100,
        contrast: 100,
        grayscale: 100,
        sepia: 0,
        saturate: 100,
        hueRotate: 0,
      },
    },
    {
      id: "vintage",
      name: "Vintage",
      filter: {
        brightness: 95,
        contrast: 90,
        grayscale: 10,
        sepia: 40,
        saturate: 80,
        hueRotate: 0,
      },
    },
    {
      id: "noir",
      name: "Noir",
      filter: {
        brightness: 90,
        contrast: 140,
        grayscale: 100,
        sepia: 0,
        saturate: 100,
        hueRotate: 0,
      },
    },
    {
      id: "sepia",
      name: "Sepia",
      filter: {
        brightness: 100,
        contrast: 100,
        grayscale: 0,
        sepia: 80,
        saturate: 100,
        hueRotate: 0,
      },
    },
  ],
  vivid: [
    {
      id: "pop",
      name: "Pop",
      filter: {
        brightness: 110,
        contrast: 120,
        grayscale: 0,
        sepia: 0,
        saturate: 150,
        hueRotate: 0,
      },
    },
    {
      id: "vibrant",
      name: "Vibrant",
      filter: {
        brightness: 115,
        contrast: 125,
        grayscale: 0,
        sepia: 0,
        saturate: 170,
        hueRotate: 0,
      },
    },
    {
      id: "lush",
      name: "Lush",
      filter: {
        brightness: 105,
        contrast: 110,
        grayscale: 0,
        sepia: 0,
        saturate: 160,
        hueRotate: 350,
      },
    },
    {
      id: "neon",
      name: "Neon",
      filter: {
        brightness: 110,
        contrast: 130,
        grayscale: 0,
        sepia: 0,
        saturate: 180,
        hueRotate: 10,
      },
    },
  ],
  warm: [
    {
      id: "sunset",
      name: "Sunset",
      filter: {
        brightness: 105,
        contrast: 110,
        grayscale: 0,
        sepia: 20,
        saturate: 130,
        hueRotate: 350,
      },
    },
    {
      id: "golden",
      name: "Golden",
      filter: {
        brightness: 105,
        contrast: 105,
        grayscale: 0,
        sepia: 30,
        saturate: 120,
        hueRotate: 0,
      },
    },
    {
      id: "amber",
      name: "Amber",
      filter: {
        brightness: 102,
        contrast: 108,
        grayscale: 0,
        sepia: 25,
        saturate: 125,
        hueRotate: 10,
      },
    },
    {
      id: "autumn",
      name: "Autumn",
      filter: {
        brightness: 100,
        contrast: 110,
        grayscale: 0,
        sepia: 25,
        saturate: 120,
        hueRotate: 355,
      },
    },
  ],
  cool: [
    {
      id: "arctic",
      name: "Arctic",
      filter: {
        brightness: 105,
        contrast: 110,
        grayscale: 0,
        sepia: 0,
        saturate: 80,
        hueRotate: 190,
      },
    },
    {
      id: "sapphire",
      name: "Sapphire",
      filter: {
        brightness: 100,
        contrast: 110,
        grayscale: 0,
        sepia: 0,
        saturate: 120,
        hueRotate: 200,
      },
    },
    {
      id: "icy",
      name: "Icy",
      filter: {
        brightness: 110,
        contrast: 105,
        grayscale: 5,
        sepia: 0,
        saturate: 90,
        hueRotate: 180,
      },
    },
    {
      id: "teal",
      name: "Teal",
      filter: {
        brightness: 100,
        contrast: 100,
        grayscale: 0,
        sepia: 0,
        saturate: 110,
        hueRotate: 160,
      },
    },
  ],
  retro: [
    {
      id: "80s",
      name: "80s",
      filter: {
        brightness: 105,
        contrast: 115,
        grayscale: 0,
        sepia: 10,
        saturate: 140,
        hueRotate: 350,
      },
    },
    {
      id: "pixel",
      name: "Pixel",
      filter: {
        brightness: 110,
        contrast: 130,
        grayscale: 0,
        sepia: 5,
        saturate: 120,
        hueRotate: 0,
      },
    },
    {
      id: "vhs",
      name: "VHS",
      filter: {
        brightness: 95,
        contrast: 120,
        grayscale: 0,
        sepia: 15,
        saturate: 110,
        hueRotate: 5,
      },
    },
    {
      id: "y2k",
      name: "Y2K",
      filter: {
        brightness: 110,
        contrast: 115,
        grayscale: 0,
        sepia: 0,
        saturate: 130,
        hueRotate: 5,
      },
    },
  ],
  cinematic: [
    {
      id: "drama",
      name: "Drama",
      filter: {
        brightness: 95,
        contrast: 140,
        grayscale: 0,
        sepia: 0,
        saturate: 110,
        hueRotate: 0,
      },
    },
    {
      id: "film",
      name: "Film",
      filter: {
        brightness: 100,
        contrast: 95,
        grayscale: 15,
        sepia: 10,
        saturate: 90,
        hueRotate: 0,
      },
    },
    {
      id: "fade",
      name: "Fade",
      filter: {
        brightness: 105,
        contrast: 90,
        grayscale: 10,
        sepia: 5,
        saturate: 85,
        hueRotate: 0,
      },
    },
    {
      id: "cinema",
      name: "Cinema",
      filter: {
        brightness: 95,
        contrast: 120,
        grayscale: 5,
        sepia: 5,
        saturate: 90,
        hueRotate: 0,
      },
    },
  ],
  modern: [
    {
      id: "minimal",
      name: "Minimal",
      filter: {
        brightness: 105,
        contrast: 95,
        grayscale: 5,
        sepia: 0,
        saturate: 90,
        hueRotate: 0,
      },
    },
    {
      id: "clean",
      name: "Clean",
      filter: {
        brightness: 108,
        contrast: 102,
        grayscale: 0,
        sepia: 0,
        saturate: 95,
        hueRotate: 0,
      },
    },
    {
      id: "tech",
      name: "Tech",
      filter: {
        brightness: 105,
        contrast: 110,
        grayscale: 5,
        sepia: 0,
        saturate: 90,
        hueRotate: 190,
      },
    },
    {
      id: "future",
      name: "Future",
      filter: {
        brightness: 110,
        contrast: 120,
        grayscale: 0,
        sepia: 0,
        saturate: 110,
        hueRotate: 170,
      },
    },
  ],
  pastel: [
    {
      id: "rose",
      name: "Rose",
      filter: {
        brightness: 105,
        contrast: 95,
        grayscale: 0,
        sepia: 10,
        saturate: 110,
        hueRotate: 340,
      },
    },
    {
      id: "lavender",
      name: "Lavender",
      filter: {
        brightness: 105,
        contrast: 95,
        grayscale: 0,
        sepia: 0,
        saturate: 100,
        hueRotate: 280,
      },
    },
    {
      id: "mint",
      name: "Mint",
      filter: {
        brightness: 105,
        contrast: 90,
        grayscale: 0,
        sepia: 0,
        saturate: 90,
        hueRotate: 140,
      },
    },
    {
      id: "dreamy",
      name: "Dreamy",
      filter: {
        brightness: 105,
        contrast: 90,
        grayscale: 0,
        sepia: 10,
        saturate: 110,
        hueRotate: 0,
      },
    },
  ],
  duotone: [
    {
      id: "crimson",
      name: "Crimson",
      filter: {
        brightness: 100,
        contrast: 120,
        grayscale: 50,
        sepia: 20,
        saturate: 150,
        hueRotate: 330,
      },
    },
    {
      id: "emerald",
      name: "Emerald",
      filter: {
        brightness: 100,
        contrast: 120,
        grayscale: 50,
        sepia: 20,
        saturate: 150,
        hueRotate: 140,
      },
    },
    {
      id: "indigo",
      name: "Indigo",
      filter: {
        brightness: 100,
        contrast: 120,
        grayscale: 50,
        sepia: 20,
        saturate: 150,
        hueRotate: 240,
      },
    },
    {
      id: "copper",
      name: "Copper",
      filter: {
        brightness: 100,
        contrast: 120,
        grayscale: 50,
        sepia: 50,
        saturate: 130,
        hueRotate: 20,
      },
    },
  ],
  effects: [
    {
      id: "glitch",
      name: "Glitch",
      filter: {
        brightness: 110,
        contrast: 150,
        grayscale: 0,
        sepia: 0,
        saturate: 140,
        hueRotate: 180,
      },
    },
    {
      id: "bloom",
      name: "Bloom",
      filter: {
        brightness: 115,
        contrast: 90,
        grayscale: 0,
        sepia: 10,
        saturate: 120,
        hueRotate: 0,
      },
    },
    {
      id: "sparkle",
      name: "Sparkle",
      filter: {
        brightness: 120,
        contrast: 110,
        grayscale: 0,
        sepia: 0,
        saturate: 130,
        hueRotate: 0,
      },
    },
    {
      id: "haze",
      name: "Haze",
      filter: {
        brightness: 110,
        contrast: 85,
        grayscale: 5,
        sepia: 5,
        saturate: 90,
        hueRotate: 0,
      },
    },
  ],
};
